package com.app.allride.driver.features.my_trips.model

data class Data(
    val actual_duration: Any,
    val assigned_driver_id: Int,
    val assigned_route_id: Int,
    val assigned_vehicle_id: Int,
    val assignment_type: Any,
    val created_at: String,
    val created_by: Any,
    val deleted_at: Any,
    val distance_covered: Any,
    val driver: Driver,
    val end_time: Any,
    val geolocations: Any,
    val id: Int,
    val latest_dispatch_activity: Int,
    val number_of_adults: Int,
    val number_of_baggages: Int,
    val number_of_children: Int,
    val number_of_infants: Int,
    val operator_id: Int,
    val passengers_count: Int,
    val reservations: List<Any>,
    val route: Route,
    val scheduled_on: String,
    val seat_available: Any,
    val solution: Solution,
    val solution_id: Int,
    val startEndStations: List<StartEndStation>,
    val start_time: Any,
    val trip_reference_number: String,
    val trip_status: Int,
    val updated_at: String,
    val updated_by: Any,
    val vehicle: Vehicle
)